#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Ba-dwi Code

# Short bio or description (displayed in the header)
description: Blog untuk kode

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://www.gravatar.com/avatar/1f380cf321159e4ec4329421a62a32f3.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: 
  flickr:
  github: baddwin
  instagram:
  linkedin: baddwin
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: baddwin
  stackoverflow: users/2536631 # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: user/slmbadwi # channel/<your_long_string> or user/<user-name>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: codebadwi

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-36990012-6

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://code.badwi.my.id

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

#markdown: redcarpet
#highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

kramdown:
 input: GFM
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  css_class: 'highlight'


# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
