baseurl = "https://aryos.id/blog/"
languageCode = "id"
title = "Aryo Sr. Blog"

publishDir = "docs"

theme = "hucore"
copyright = "&copy; 2017 | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "codebadwi"
googleAnalytics = "UA-36990012-6"

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
posts = "/:year/:month/:title/"

[params]
description = "Blog untuk kode"
author = "Aryo Sr."
keywords = []
sharingicons = true
displayauthor = true
gtm_id = "GTM-T8H2TXC"
gtm_ga = true
gtm_datalayer = "basic"

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "php"]

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"

[[params.social]]
name = "github"
url = "https://github.com/aryo-sr"
fa_icon = "fa-github"

[[params.social]]
name = "linkedin"
url = "https://bit.ly/aryo-sr"
fa_icon = "fa-linkedin"

