baseurl = "https://code.badwi.my.id/"
languageCode = "id"
title = "Ba-dwi Code"

publishDir = "docs"

theme = "hucore"
copyright = "&copy; 2017 | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "codebadwi"
googleAnalytics = "UA-36990012-6"

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
posts = "/:year/:month/:title/"

[params]
description = "Blog untuk kode"
author = "Badwi"
keywords = []
sharingicons = true
displayauthor = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "php"]

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"

[[params.social]]
name = "github"
url = "https://github.com/baddwin"
fa_icon = "fa-github"

[[params.social]]
name = "twitter"
url = "https://twitter.com/baddwin"
fa_icon = "fa-twitter"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/baddwin"
fa_icon = "fa-linkedin-square"

[[params.social]]
name = "instagram"
url = "https://www.instagram.com/baddwin"
fa_icon = "fa-instagram"

[[params.social]]
name = "medium"
url = "https://medium.com/@baddwin"
fa_icon = "fa-medium"

[[params.social]]
name = "lastfm"
url = "https://www.last.fm/user/baddwin"
fa_icon = "fa-lastfm"
