# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
    paths:
      - content/**
      - layouts/**
      - static/**
      - config.toml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  nuxt:
    environment:
      name: Build Nuxt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: aryo-sr/aryo-sr.github.io
          ref: deploy
          path: nuxt

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        working-directory: nuxt
        run: yarn install

      - name: Generate
        working-directory: nuxt
        run: yarn build && yarn generate
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          WEBSITE_NAME: ${{ vars.WEBSITE_NAME }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: root_nuxt
          path: ${{ github.workspace }}/nuxt/dist/
          retention-days: 3

  hugo:
    environment:
      name: Build Hugo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          path: hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
        working-directory: hugo

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: blog_hugo
          path: ${{ github.workspace }}/hugo/docs/
          retention-days: 1

  # Deployment job
  deploy:
    needs: [nuxt, hugo]
    environment:
      name: Push Pages
      url: ${{ steps.cf_pages.outputs.alias }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
#      name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact hugo
        uses: actions/download-artifact@v3
        id: download

      - name: Display structure of downloaded files
        run: ls -l
        working-directory: ${{steps.download.outputs.download-path}}

      - name: Unifying files
        run: mv ${{steps.download.outputs.download-path}}/blog_hugo/blog ${{steps.download.outputs.download-path}}/root_nuxt/

    # Run a build step here if your project requires

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        id: cf_pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: aryosid-root
          directory: root_nuxt
          # workingDirectory: blog
          branch: deploy
          # Optional: Enable this if you want to have GitHub Deployments triggered
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
