name: Release Manually

on:
  # push:
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    environment:
      name: Publish Compiled
      url: ${{ steps.soft_release.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/github-script@v6
        with:
          script: |
            let lastSucceededRun = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "hugo.yml",
              status: "completed",
              per_page: 1
            });
            console.log(lastSucceededRun.data ?? 'error');
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: lastSucceededRun.data.workflow_runs[0].id,
            });
            console.log(allArtifacts.data ?? 'error');
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "blog_hugo"
            })[0];
            console.log(matchArtifact);
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/blog_hugo.zip`, Buffer.from(download.data));

      - name: Show files
        run: ls -l

      - name: Get latest tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          prefix: v

      - name: Get next version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Release
        id: soft_release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/head/')
        with:
          files: blog_hugo.zip
          name: ${{ steps.semvers.outputs.v_patch }}
          tag_name: ${{ steps.semvers.outputs.v_patch }}

