name: Release Compiled HTML

on:
  workflow_run:
    workflows:
      - Deploy Hugo site to Pages
    types:
      - completed

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    environment:
      name: Publish Compiled
      url: ${{ steps.soft_release.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/github-script@v6
        with:
          script: |
            let lastSucceededRun = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "hugo.yml",
              status: "completed",
              per_page: 1
            });
            console.log(lastSucceededRun.data ?? 'error');
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: lastSucceededRun.data.workflow_runs[0].id,
            });
            console.log(allArtifacts.data ?? 'error');
            if (allArtifacts.total_count !== undefined && allArtifacts.total_count > 1) {
              let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name == "blog_hugo"
              })[0];
              console.log(matchArtifact);
              let download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: matchArtifact.id,
                 archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/blog_hugo.zip`, Buffer.from(download.data));
            }

      - name: Show files
        run: ls -l

      - name: Get latest tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          prefix: v

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        id: soft_release
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: blog_hugo.zip
          name: ${{ steps.vars.outputs.short_sha }}
          tag_name: ${{ steps.previoustag.outputs.tag }} + '_' + ${{ steps.vars.outputs.short_sha }}
